# Generated by Django 5.2.1 on 2025-05-27 14:02

from django.db import migrations, models

import utils.snowflake_helper


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(default=utils.snowflake_helper.get_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigIntegerField(default=utils.snowflake_helper.get_snowflake_id, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
