# Generated by Django 5.2.1 on 2025-05-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"verbose_name": "пост", "verbose_name_plural": "Посты"},
        ),
    ]
