# Generated by Django 5.2.1 on 2025-05-29 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0003_alter_chatmember_chat_alter_chatmember_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"verbose_name": "чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterField(
            model_name="messages",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
