# Generated by Django 5.2.1 on 2025-05-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(
                blank=True,
                default="users_images/default_image.png",
                null=True,
                upload_to="users_images/",
            ),
        ),
    ]
