# Generated by Django 5.2.1 on 2025-05-28 15:04

from django.db import migrations, models

import utils.image_rename


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="user_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=utils.image_rename.rename_uploaded_file
            ),
        ),
    ]
