# Generated by Django 5.2.1 on 2025-05-29 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_customuser_user_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
